- name: Preparing the build-node
  hosts: '{{ instanse }}'
  become: true
  vars:
    instanse: build
    repository: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
    package:
      - 'default-jdk'
      - 'maven'
      - 'git'
    workdir: '/opt/app'

  tasks:
  - name: Make sure the packages are present
    apt:
      name: '{{ package }}'
      state: present
      cache_valid_time: 10000

  - name: Fetch application on git
    git:
      repo: '{{ repository }}'
      dest: '{{ workdir }}'

  - name: build webapp
    shell: mvn clean package
    args:
      chdir: '{{ workdir }}'

  - name: Fetch webapp-file
    synchronize:
      mode: pull
      src: '{{ workdir }}/target/hello-1.0.war'
      dest: '{{ workdir }}/hello-1.0.war'

  - name: Clear source
    file:
      state: absent
      path: '{{ workdir }}'


- name: Preparing the prod-node
  hosts: '{{ instanse }}'
  become: true
  vars:
    instanse: prod
    package: 'tomcat9'
    app_path: '/opt/app/hello-1.0.war'
    web_path: '/var/lib/tomcat9/webapps/hello-1.0.war'
  tasks:

  - name: Ensure the package is present
    apt:
      name: '{{ package }}'
      state: present
      cache_valid_time: 10000

  - name: Copy webapp-file
    synchronize:
      src: '{{ app_path }}'
      dest: '{{ web_path }}'

  - name: Ensure tomcat is started
    service:
      name: '{{ package }}'
      state: started

  - name: Clear source
    file:
      state: absent
      path: '{{ app_path }}'
    delegate_to: localhost